### ISSUE TITLE
Task #35718 for KitPvP v2.1.7 generated an exception

### ISSUE THREAD

**Issue by walkwithshibin** [cervinakuy/KitPvP#125] opened 2021-02-05 10:09 UTC
**Problem**
 [KitPvP] Task #35718 for KitPvP v2.1.7 generated an exception
 
  [10:07:23 WARN]: [KitPvP] Task #54762 for KitPvP v2.1.7 generated an exception
java.lang.NullPointerException
        at com.planetgallium.kitpvp.listener.ItemListener$3.run(ItemListener.java:509) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]

**What I have tried**
I don't know the fix

**Screenshot of /KP debug**
![Screenshot 2021-02-05 153705](https://user-images.githubusercontent.com/38835725/107019810-21049280-67c8-11eb-86b0-388f4d676f03.png)

**Any additional information (copy of config files, screenshots, videos, etc.)**

**Comment by cervinakuy** [comment] 2021-02-06 02:44
Thanks for reporting. I have found the cause and it be will fixed soon when I get back home.

**Comment by cervinakuy** [comment] 2021-02-08 15:53
Fixed in [82a94fb](https://github.com/cervinakuy/KitPvP/commit/82a94fbe4edec377a577581e40eaddd83f499b64). This will be included in the next update.

**Closed by cervinakuy** 2021-02-08 15:53 UTC
Labels: help wanted
