### ISSUE TITLE
Error when throwing splash potions

### ISSUE THREAD

**Issue by robbbak** [cervinakuy/KitPvP#115] opened 2021-01-04 08:47 UTC
**Description of the bug**
I'm on spigot version 1.8.8 and when throwing a potion i get this error. It doesnt even needs to be thrown on a player.
The potions that I throw come from the kit, I replaced the stew with potions of healing II.
I made the potions in the yml like this:
```
Material: POTION
      Type: SPLASH_POTION
      Effects:
        HEAL:
          Amplifier: 2
          splash: true
```

**Screenshot of /kp debug**
https://prnt.sc/wftb7p

**Additional screenshots or video (if applicable)**

**Pastebin.com of any relevant .yml files (if applicable)**
https://pastebin.com/g2MTzY93

**Comment by cervinakuy** [comment] 2021-01-08 16:25
Thanks for taking the time to report this problem. However, this is a duplicate of #112. This bug will be fixed in the next version.

**Closed by cervinakuy** 2021-01-08 16:25 UTC
Labels: bug
